services:
  csa-worker:
    build: .
    restart: unless-stopped
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
    networks:
      - casm_isim_test_network

networks:
  casm_isim_test_network:
    name: casm_isim_test_network
